//
//  StyleKit.h
//  PaypointSDK
//
//  Created by Rob Nash on 22/04/2015.
//  Copyright (c) 2015 Paypoint. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKit : NSObject

// Drawing Methods
+ (void)drawFeedbackBubbleWithFrame: (CGRect)frame message: (NSString*)message;

@end
